# Generated by Django 4.0.5 on 2022-12-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputlink', models.CharField(max_length=20000)),
                ('Uuid', models.CharField(max_length=10)),
            ],
        ),
    ]
